# Generated by Django 4.2.5 on 2023-09-04 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidit', '0002_remove_customuser_is_bidder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_bidder',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='wallet_balance',
            field=models.IntegerField(null=True),
        ),
    ]
